# Change baseurl before deploy
baseurl = "https://shuban-789.github.io/"
languageCode = "en-us"
title = "Shuban Pal"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

[[songs]]
spotify_url = "https://open.spotify.com/track/68hjxmQouj1VRaUg8BHWAV?si=440dda2e57d74689"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/4SquYNaAEtpiTLT5T8tkx6?si=e006b551f3d444da"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/6B0uQN8uD1arVAOI4ZYAqJ?si=cd663e56e0d9466e"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/58ZYYZ8UwYcioNnwMgQOc8?si=d3896bbdc3994a08"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/3QpItBJGYu3gvkiLocgBSK?si=13524835e5c84011"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/6hoahPnjmQ4dNtZrn2SjPS?si=08a0ab20b12a44e5"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/4sUTagdmyuyAxd7RvbygpQ?si=32da8bc4072e4b4c"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/69jGxyfw3lzGGYf78jdkpF?si=ac37c0ff9a9e4d68"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/2ff0Hy1uymLoiiHD1nmeOB?si=6bb64bcf934a4b64"
start_at = 0

[[songs]]
spotify_url = "https://open.spotify.com/track/6Lph4zADq2K62XAjVaMWxR?si=0b8b107f8cc7491b"
start_at = 0